Prevent marshal empty error
parkhub/go-parkhub-logger pull request #4
Opened 2021-07-26 18:18 UTC by GregWWalters

Basic error types marshal to JSON as empty objects. This adds a check for error types in `logMessage.Metadata` that don't implement json.Marshaller and replaces them their Error() result.

Also adds an early return in SetupLogger.

2021-08-04 14:31 UTC, colinc86 requested changes
Just a comment typo. Everything looks great!

2021-08-04 14:31 UTC, colinc86 commented on logmessage.go
> +	// any errors in the slice
Any any!

2021-08-04 14:31 UTC, colinc86 commented on logmessage.go
> +	// any errors in the slice
```suggestion
	// errors in the slice
```

2021-08-05 18:28 UTC, colinc86 approved these changes

2021-08-17 16:08 UTC, daytonpe approved these changes

2021-08-18 16:11 UTC, merged